apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-news-api
  labels:
    app: fake-news
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fake-news
  template:
    metadata:
      labels:
        app: fake-news
    spec:
      containers:
      - name: api
        image: fake-news-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
