apiVersion: v1
kind: Secret
metadata:
  name: fake-news-secrets
type: Opaque
data:
  vault-token: ZGV2LW9ubHktdG9rZW4=
  jenkins-user: YWRtaW4=
  jenkins-pass: OTMzMTFlZWI0MmIzNDQzZGI2ZGVhZTUxZGZmMGU1NzE=
